import './global.css';
import { Heading } from '../shared-ui/Typography/Heading';
import { Container } from '../shared-ui';
import Link from 'next/link';

export const metadata = {
  title: 'Welcome to client',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de">
      <body>
        <main className="my-8">
          <Container>
            <Link href={'/'}>
              <Heading tag="h1">DAV</Heading>
            </Link>
          </Container>
          {children}
        </main>
      </body>
    </html>
  );
}
