### Get api
GET http://localhost:3000/api

### GET files
GET http://localhost:3000/api/file

### POST process file by id
POST http://localhost:3000/api/file/1/process

### Post api
POST http://localhost:3000/api/file/upload
content-type: application/json

{
    "name": "some filename"
}

### Delete file
DELETE http://localhost:3000/api/file/1


## Course

### GET courses
GET http://localhost:3000/api/course

## Auth

### GET profile
GET http://localhost:3000/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyaW5hQGVtYWlsLmNvbSIsInV1aWQiOiI5OWNmYjE1MC04MGU4LTQyNzctYWNjOC04YTlkN2Q5NjM2MDMiLCJpYXQiOjE3MDQ2NTA2NTYsImV4cCI6MTcwNzI0MjY1Nn0.mnrY4rW3yTQz1zKFR6sGiwrMrqr1KsAapPwMT6DI5HM

### POST login
POST http://localhost:3000/api/auth/login
content-type: application/json

{"username": "arina@email.com", "password": "changeme"}

### POST signup
POST http://localhost:3000/api/auth/signup
content-type: application/json

{"email": "arina@email.com", "password": "changeme", "name": "Arina", "lastname": "Doe"}