### Get api
GET http://localhost:3000/api

### GET files
GET http://localhost:3000/api/file

### Post api
POST http://localhost:3000/api/file/upload
content-type: application/json

{
    "name": "some filename"
}

### Delete file
DELETE http://localhost:3000/api/file/1